name: fontrapak
title: Fontra Pak (Unofficial snap package)
base: core22
summary: Browser-based variable-first font editor
description: |
  Fontra is an open-source, browser-based, cross-platform, variable-first
  font editor. Fontra extends the boundaries of what current font editors
  can do. Originally developed to make the design and production of large
  CJK fonts more efficient, Fontra provides deeper integration of
  variable font technology and improved usability of variable
  components as design elements.

grade: stable
confinement: strict
adopt-info: fontrapak

architectures:
  - build-on: amd64
    build-for: amd64

parts:
  fontrapak:
    plugin: dump
    # Snapcraft will download this automatically with network access
    source: https://github.com/fontra/fontra-pak/releases/latest/download/FontraPakUbuntu.tgz
    source-type: tar
    build-packages:
      - curl
      - jq
    override-pull: |
      # First, let snapcraft download the source using its built-in mechanism
      snapcraftctl pull
      
      # Fetch version from GitHub API
      echo "Fetching latest release tag from fontra/fontra-pak..."
      LATEST_TAG=$(curl -s https://api.github.com/repos/fontra/fontra-pak/releases/latest | jq -r '.tag_name')
      
      if [ "$LATEST_TAG" = "null" ] || [ -z "$LATEST_TAG" ]; then
        echo "ERROR: Failed to fetch latest release tag"
        craftctl set version="0.0.1+unknown"
      else
        # Remove 'v' prefix if present
        VERSION="${LATEST_TAG#v}"
        echo "Setting snap version to '$VERSION'"
        craftctl set version="$VERSION"
      fi
      
    organize:
      fontrapak/fontrapak: bin/fontrapak
      
    stage-packages:
      - libgl1
      - libegl1
      - libgl1-mesa-glx
      - libxcb-cursor0
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcb-randr0
      - libxcb-xfixes0
      - libxkbcommon0
      - libqt6gui6
      - libqt6core6
      - libqt6widgets6
      - libstdc++6
      - qt6-qpa-plugins

icon: snap/gui/fontrapak.svg
license: GPL-3.0+

plugs:
  shared-memory:
    private: true

apps:
  fontrapak:
    command: bin/fontrapak
    desktop: snap/gui/fontrapak.desktop
    environment:
      QT_QPA_PLATFORM: xcb
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt6/plugins/platforms
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET
    plugs:
      - x11
      - opengl
      - network
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - wayland
