
name: fontrapak
title: Fontra Pak (Unofficial snap package)
base: core22 # the base snap is the execution environment for this snap
summary: Browser-based variable-first font editor # 79 char long summary
description: |
  Fontra is an open-source, browser-based, cross-platform, variable-first
  font editor. Fontra extends the boundaries of what current font editors
  can do. Originally developed to make the design and production of large
  CJK fonts more efficient, Fontra provides deeper integration of
  variable font technology and improved    usability of variable
  components as design elements.

grade: stable
confinement: strict
adopt-info: fontrapak
architectures:
  - build-on: amd64
    build-for: amd64
parts:
  fontrapak:
    plugin: dump
    # Add source: . back to satisfy the validator, even though we download manually
    source: .
    build-packages:
      - wget
      - tar
    override-pull: |
      snapcraftctl pull # Run default pull actions first

      # Change directory to where Snapcraft expects source for this part
      cd "$SNAPCRAFT_PART_SRC"

      
      DOWNLOAD_URL="https://github.com/mitradranirban/fontra-pak-linux/releases/latest/download/fontrapak.tgz"
      ARCHIVE_FILE="fontrapak.tgz"

      echo "Attempting to download $DOWNLOAD_URL..."
      wget --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" \
           "$DOWNLOAD_URL" -O "$ARCHIVE_FILE"

      if [ ! -f "$ARCHIVE_FILE" ] || [ ! -s "$ARCHIVE_FILE" ]; then
           echo "ERROR: Failed to download $ARCHIVE_FILE from $DOWNLOAD_URL"
           exit 1
      fi
      echo "Download successful."

      echo "Extracting $ARCHIVE_FILE..."
      tar -xzf "$ARCHIVE_FILE"
      echo "Extraction complete."
      
      # --- Read version.txt FROM THE EXTRACTED FILES and set snap version ---
      if [ -f "fontrapak/version.txt" ]; then
          # Read version, removing potential trailing newline
          VERSION_FROM_FILE=$(cat fontrapak/version.txt | tr -d '\n')
          echo "Setting snap version to '$VERSION_FROM_FILE' from extracted version.txt"
          # Set the snap's overall version using snapcraftctl
          craftctl set version="$VERSION_FROM_FILE"
      else
          # Handle error: version.txt not found in archive
          echo "ERROR: fontrapak/version.txt not found within the extracted archive $ARCHIVE_FILE"
          craftctl set version="0.1dev"
      fi
      # ---------------------------------------------------------------------

      # Remove the archive after extraction and version setting
      rm "$ARCHIVE_FILE"

     
    organize:
      fontrapak/fontrapak: bin/fontrapak # Moves the extracted binary to bin/fontrapak
    stage-packages:
      - libgl1
      - libegl1
      - libxcb-cursor0
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcb-randr0
      - libxcb-xfixes0
      - libxkbcommon0
      - libqt6gui6         
      - libqt6core6        
      - libqt6widgets6     
      - libstdc++6
      - qt6-qpa-plugins    


icon: snap/gui/fontrapak.svg
license: GPL-3.0+

plugs:
  shared-memory:
    private: true

apps:
  fontrapak:
    command:  bin/fontrapak
    desktop: snap/gui/fontrapak.desktop
    environment:
      QT_QPA_PLATFORM: xcb  
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt6/plugins/platforms  
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa 
    plugs:
      - x11
      - opengl
      - network  
      - home  
      - removable-media  
      - desktop
      - desktop-legacy
      - wayland  
