name: fontrapak
title: Fontra Pak (Unofficial snap package)
base: core22
summary: Browser-based variable-first font editor
description: |
  Fontra is an open-source, browser-based, cross-platform, variable-first
  font editor. Fontra extends the boundaries of what current font editors
  can do. Originally developed to make the design and production of large
  CJK fonts more efficient, Fontra provides deeper integration of
  variable font technology and improved usability of variable
  components as design elements.

# Metadata fields to suppress linter warnings
website:
  - https://fontra.xyz
  - https://docs.fontra.xyz

source-code:
  - https://github.com/fontra/fontra-pak
  - https://github.com/fontra/fontra

issues:
  - https://github.com/fontra/fontra-pak/issues

contact:
  - https://fontra.xyz

grade: stable
confinement: strict
adopt-info: fontrapak

architectures:
  - build-on: amd64
    build-for: amd64

parts:
  fontrapak:
    plugin: dump
    source: .
    build-packages:
      - wget
      - tar
      - curl
      - jq
    override-pull: |
      craftctl default
      
      # Change directory to where Snapcraft expects source for this part
      cd "$CRAFT_PART_SRC"
      
      # Get the latest release tag from GitHub API
      echo "Fetching latest release information from fontra/fontra-pak..."
      LATEST_RELEASE=$(curl -s https://api.github.com/repos/fontra/fontra-pak/releases/latest)
      LATEST_TAG=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')
      
      if [ "$LATEST_TAG" = "null" ] || [ -z "$LATEST_TAG" ]; then
        echo "ERROR: Failed to fetch latest release tag"
        exit 1
      fi
      
      echo "Latest release tag: $LATEST_TAG"
      
      # Set the snap version from the release tag (remove 'v' prefix if present)
      VERSION="${LATEST_TAG#v}"
      echo "Setting snap version to '$VERSION'"
      craftctl set version="$VERSION"
      
      # Download the binary from the latest release
      DOWNLOAD_URL="https://github.com/fontra/fontra-pak/releases/latest/download/FontraPakUbuntu.tgz"
      ARCHIVE_FILE="FontraPakUbuntu.tgz"
      
      echo "Attempting to download $DOWNLOAD_URL..."
      wget --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" \
        "$DOWNLOAD_URL" -O "$ARCHIVE_FILE"
      
      if [ ! -f "$ARCHIVE_FILE" ] || [ ! -s "$ARCHIVE_FILE" ]; then
        echo "ERROR: Failed to download $ARCHIVE_FILE from $DOWNLOAD_URL"
        exit 1
      fi
      
      echo "Download successful."
      echo "Extracting $ARCHIVE_FILE..."
      tar -xzf "$ARCHIVE_FILE"
      echo "Extraction complete."
      
      # List contents to verify structure
      echo "Archive contents:"
      ls -la
      
      # Remove the archive after extraction
      rm "$ARCHIVE_FILE"
      
    organize:
      fontrapak: bin/fontrapak
      
    stage-packages:
      - libgl1
      - libegl1
      - libgl1-mesa-glx
      - libxcb-cursor0
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcb-randr0
      - libxcb-xfixes0
      - libxkbcommon0
      - libqt6gui6
      - libqt6core6
      - libqt6widgets6
      - libstdc++6
      - qt6-qpa-plugins

icon: snap/gui/fontrapak.svg
license: GPL-3.0+

plugs:
  shared-memory:
    private: true

apps:
  fontrapak:
    command: bin/fontrapak
    desktop: snap/gui/fontrapak.desktop
    environment:
      QT_QPA_PLATFORM: xcb
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt6/plugins/platforms
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET
    plugs:
      - x11
      - opengl
      - network
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - wayland
