

name: fontrapak
title: Fontra Pak (Unofficial snap package)
base: core22 # the base snap is the execution environment for this snap
version: '0.1.dev11293+g1fc208d'
summary: Browser-based variable-first font editor # 79 char long summary
description: |
  Fontra is an open-source, browser-based, cross-platform, variable-first
  font editor. Fontra extends the boundaries of what current font editors
  can do. Originally developed to make the design and production of large
  CJK fonts more efficient, Fontra provides deeper integration of
  variable font technology and improved    usability of variable
  components as design elements.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    build-for: amd64

parts:
  fontrapak:
    plugin: dump
    source: .
    organize:
      fontrapak: bin/fontrapak
    stage-packages:
      - libgl1
      - libegl1
      - libxcb-cursor0  # Add this explicitly
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcb-randr0
      - libxcb-xfixes0
      - libxkbcommon0
      - libqt5gui5        # Often needed for Qt applications
      - libqt5core5a      # Core Qt libraries
      - libqt5widgets5    # If your application uses widgets
      - libqt6gui6        # If your application uses Qt 6
      - libqt6core6       # Core Qt 6 libraries
      - libqt6widgets6    # If your application uses Qt 6 widgets
      - libstdc++6        # Standard C++ library (often a dependency)


icon: snap/gui/fontrapak.svg
license: GPL-3.0+

plugs:
  shared-memory:
    private: true

apps:
  fontrapak:
    command: bin/fontrapak
    #extensions: [gnome]
    environment:
      QT_QPA_PLATFORM: xcb # Required for Qt applications in a snap (PyInstaller often uses Qt)
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/platforms:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt6/plugins/platforms # Explicitly set plugin path
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa # Include Mesa libraries if needed
    plugs:
      - x11
      - unity7
      - opengl
      - network # if any network access is needed
      - home # if it needs access to user home directory
      - removable-media # if it needs access to removable media.
      - desktop
      - desktop-legacy
      - wayland # for wayland support
