name: Update Version File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install the package (editable mode if needed)
      - name: Install the package
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/googlefonts/fontra.git

      # Step 4: Query the __version__ string
      - name: Query __version__ string
        id: query-version
        run: |
          echo $(python -c "import fontra; print(fontra.__version__)") > version.txt

      # Step 5: Commit and push version.txt to the repository
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version.txt
          git commit -m "Update version.txt with the current version of fontra"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
